
CREATE TABLE "bm_ip_bans" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "ip" VARBINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "created" INT NOT NULL,
  "updated" INT NOT NULL,
  "expires" INT NOT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_ip_ban_records" (
  "id" INT NOT NULL,
  "ip" VARBINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "expired" INT NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "pastActor_id" BINARY(16) NOT NULL,
  "pastCreated" INT NOT NULL,
  "created" INT NOT NULL,
  "createdReason" CHARACTER VARYING(255) NOT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_ip_mutes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "ip" VARBINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "created" INT NOT NULL,
  "updated" INT NOT NULL,
  "expires" INT NOT NULL,
  "soft" TINYINT DEFAULT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_ip_mute_records" (
  "id" INT NOT NULL,
  "ip" VARBINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "expired" INT NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "pastActor_id" BINARY(16) NOT NULL,
  "pastCreated" INT NOT NULL,
  "created" INT NOT NULL,
  "createdReason" CHARACTER VARYING(255) NOT NULL,
  "soft" TINYINT DEFAULT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_ip_range_bans" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "fromIp" VARBINARY(16) NOT NULL,
  "toIp" VARBINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "created" INT NOT NULL,
  "updated" INT NOT NULL,
  "expires" INT NOT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_ip_range_ban_records" (
  "id" INT NOT NULL,
  "fromIp" VARBINARY(16) NOT NULL,
  "toIp" VARBINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "expired" INT NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "pastActor_id" BINARY(16) NOT NULL,
  "pastCreated" INT NOT NULL,
  "created" INT NOT NULL,
  "createdReason" CHARACTER VARYING(255) NOT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_name_bans" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" CHARACTER VARYING(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "created" INT NOT NULL,
  "updated" INT NOT NULL,
  "expires" INT NOT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_name_ban_records" (
  "id" INT NOT NULL,
  "name" CHARACTER VARYING(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "expired" BIGINT NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "pastActor_id" BINARY(16) NOT NULL,
  "pastCreated" INT NOT NULL,
  "created" INT NOT NULL,
  "createdReason" CHARACTER VARYING(255) NOT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_players" (
  "id" BINARY(16) NOT NULL,
  "name" CHARACTER VARYING(16) NOT NULL,
  "ip" VARBINARY(16) NOT NULL,
  "lastSeen" INT NOT NULL
);

CREATE TABLE "bm_player_bans" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "player_id" BINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "created" INT NOT NULL,
  "updated" INT NOT NULL,
  "expires" INT NOT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_player_ban_records" (
  "id" INT NOT NULL,
  "player_id" BINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "expired" BIGINT NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "pastActor_id" BINARY(16) NOT NULL,
  "pastCreated" INT NOT NULL,
  "created" INT NOT NULL,
  "createdReason" CHARACTER VARYING(255) NOT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_player_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "player_id" BINARY(16) NOT NULL,
  "ip" VARBINARY(16) NOT NULL,
  "join" INT NOT NULL,
  "leave" INT NOT NULL
);

CREATE TABLE "bm_player_kicks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "player_id" BINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "created" INT NOT NULL
);

CREATE TABLE "bm_player_mutes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "player_id" BINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "created" INT NOT NULL,
  "updated" INT NOT NULL,
  "expires" INT NOT NULL,
  "soft" TINYINT DEFAULT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_player_mute_records" (
  "id" INT NOT NULL,
  "player_id" BINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "expired" BIGINT NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "pastActor_id" BINARY(16) NOT NULL,
  "pastCreated" INT NOT NULL,
  "created" INT NOT NULL,
  "createdReason" CHARACTER VARYING(255) NOT NULL,
  "soft" TINYINT DEFAULT NULL,
  "silent" TINYINT DEFAULT NULL
);

CREATE TABLE "bm_player_notes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "player_id" BINARY(16) NOT NULL,
  "message" CHARACTER VARYING(255) NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "created" INT NOT NULL
);

CREATE TABLE "bm_player_reports" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "player_id" BINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "state_id" INT NOT NULL DEFAULT 1,
  "assignee_id" BINARY(16) DEFAULT NULL,
  "created" INT NOT NULL,
  "updated" INT NOT NULL
);

CREATE TABLE "bm_player_report_commands" (
  "id" INT NOT NULL,
  "report_id" INT NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "command" CHARACTER VARYING(255) NOT NULL,
  "args" CHARACTER VARYING(255) NOT NULL,
  "created" INT NOT NULL,
  "updated" INT NOT NULL
);

CREATE TABLE "bm_player_report_comments" (
  "id" INT NOT NULL,
  "report_id" INT NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "comment" CHARACTER VARYING(255) NOT NULL,
  "created" INT NOT NULL,
  "updated" INT NOT NULL
);

CREATE TABLE "bm_player_report_locations" (
  "id" INT NOT NULL,
  "report_id" INT NOT NULL,
  "player_id" BINARY(16) NOT NULL,
  "world" CHARACTER VARYING(255) NOT NULL,
  "x" double NOT NULL,
  "y" double NOT NULL,
  "z" double NOT NULL,
  "pitch" float NOT NULL,
  "yaw" float NOT NULL
);

CREATE TABLE "bm_player_report_states" (
  "id" INT NOT NULL,
  "name" CHARACTER VARYING(255) NOT NULL
);

CREATE TABLE "bm_player_warnings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "player_id" BINARY(16) NOT NULL,
  "reason" CHARACTER VARYING(255) NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "created" INT NOT NULL,
  "expires" INT NOT NULL,
  "read" TINYINT DEFAULT NULL,
  "points" double DEFAULT NULL
);

CREATE TABLE "bm_rollbacks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "player_id" BINARY(16) NOT NULL,
  "actor_id" BINARY(16) NOT NULL,
  "type" CHARACTER VARYING(255) NOT NULL,
  "created" INT NOT NULL,
  "expires" INT NOT NULL
);
