<!--
  ~ LibertyBans-fabric
  ~ Copyright © 2026 Anand Beh
  ~
  ~ LibertyBans-fabric is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Lesser General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ LibertyBans-fabric is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public License
  ~ along with LibertyBans-fabric. If not, see <https://www.gnu.org/licenses/>
  ~ and navigate to version 3 of the GNU Lesser General Public License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>space.arim.libertybans</groupId>
        <artifactId>bans-env</artifactId>
        <version>1.2.0-M1-SNAPSHOT</version>
    </parent>

    <artifactId>bans-env-fabric</artifactId>

    <properties>
        <deployment.deploy-url>https://maven.cloudsmith.io/anand-beh/lesser-gpl3/</deployment.deploy-url>

        <fabric.loader_version>0.19.2</fabric.loader_version>
        <fabric.minecraft_version>26.2</fabric.minecraft_version>
        <fabric.adventure_platform_version>7.1.1</fabric.adventure_platform_version>
    </properties>

    <licenses>
        <license>
            <name>GNU Lesser General Public License, Version 3</name>
            <url>https://www.gnu.org/licenses/lgpl-3.0-standalone.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <build>
        <!--
        We employ a multistage process in order to prepare, execute, process, and clean up a Gradle build.

        1. Fill a temporary local repository with the artifacts we need to depend upon
        2. Copy resources in src/build/resources, to pass pom properties into gradle.properties
        3. Copy fabric.mod.json from src/mod/resources
        4. Execute the Gradle build on command line
        5. After successful build, use the built jar as this module's jar, and attach the mod jar with "mod" classifier
        6. When `mvn clean` is requested, delete Gradle build data directories
        -->
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <!-- 1. -->
                    <execution>
                        <id>transfer-build-artifacts</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <useRepositoryLayout>true</useRepositoryLayout>
                            <addParentPoms>true</addParentPoms>
                            <copyPom>true</copyPom>
                            <outputDirectory>${project.build.directory}/maven/build-artifact-repo</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-resources</id>
                        <phase>none</phase>
                    </execution>
                    <!-- 1.
                    <execution>
                        <id>fill-in-local-repo</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/maven/local-repo</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${settings.localRepository}</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution> -->
                    <!-- 2. -->
                    <execution>
                        <id>copy-gradle-properties</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>src/build/resources</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                            <outputDirectory>.</outputDirectory>
                            <encoding>UTF-8</encoding>
                            <propertiesEncoding>UTF-8</propertiesEncoding>
                        </configuration>
                    </execution>
                    <!-- 3. -->
                    <execution>
                        <id>copy-fabric-mod-json</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>src/mod/resources</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                            <outputDirectory>bans-env-fabric-mod/target/maven/generated-resources</outputDirectory>
                            <encoding>UTF-8</encoding>
                            <propertiesEncoding>UTF-8</propertiesEncoding>
                        </configuration>
                    </execution>
                    <!-- 5 -->
                    <execution>
                        <id>prepare-main-artifact</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>bans-env-fabric/target/libs</directory>
                                </resource>
                            </resources>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                    <!-- 4 -->
                    <execution>
                        <id>build-gradle</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <arguments>
                                <argument>build</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <executable>./gradlew</executable>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <!-- 5 -->
                    <execution>
                        <id>attach-fabric-artifacts</id>
                        <phase>package</phase>
                        <goals>
                            <goal>attach-artifact</goal>
                        </goals>
                        <configuration>
                            <artifacts>
                                <artifact>
                                    <file>bans-env-fabric-mod/target/libs/bans-env-fabric-mod-${project.version}.jar</file>
                                    <type>jar</type>
                                    <classifier>mod</classifier>
                                </artifact>
                            </artifacts>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <configuration>
                    <!-- 6 -->
                    <filesets>
                        <fileset>
                            <directory>.</directory>
                            <includes>
                                <include>**/.gradle/**</include>
                                <include>bans-env-fabric/target/**</include>
                                <include>bans-env-fabric-mod/target/**</include>
                            </includes>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <!-- This turns out to be needed to replace the original jar -->
                        <id>default-jar</id>
                        <phase>prepare-package</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>skip-all-tests</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>build-gradle</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <arguments>
                                        <argument>build</argument>
                                        <argument>-x</argument>
                                        <argument>test</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>space.arim.libertybans</groupId>
            <artifactId>bans-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>space.arim.libertybans</groupId>
            <artifactId>bans-bootstrap</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>space.arim.libertybans</groupId>
            <artifactId>bans-env-adventure5-common</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
