<!--
  ~ LibertyBans-bootstrap
  ~ Copyright © 2026 Anand Beh
  ~
  ~ LibertyBans-bootstrap is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Lesser General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ LibertyBans-bootstrap is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public License
  ~ along with LibertyBans-bootstrap. If not, see <https://www.gnu.org/licenses/>
  ~ and navigate to version 3 of the GNU Lesser General Public License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>space.arim.libertybans</groupId>
		<artifactId>bans-bootstrap-parent</artifactId>
		<version>1.2.0-M1-SNAPSHOT</version>
	</parent>

	<groupId>space.arim.libertybans.it</groupId>
	<artifactId>invoker-it-setup</artifactId>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<executions>
					<execution>
						<id>prepare-invoker-local-repo</id>
						<phase>pre-integration-test</phase>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-invoker-plugin</artifactId>
				<executions>
					<execution>
						<id>test-api-consumers</id>
						<phase>none</phase>
					</execution>
					<execution>
						<id>verify-api-consumers</id>
						<phase>none</phase>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<!-- Miscellaneous dependencies, needed by invoker projects -->
		<dependency>
			<groupId>org.yaml</groupId>
			<artifactId>snakeyaml</artifactId>
			<version>1.28</version>
		</dependency>
		<dependency>
			<groupId>space.arim.libertybans.dep</groupId>
			<artifactId>dep-floodgate-api</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>space.arim.libertybans.dep</groupId>
			<artifactId>dep-waterfall-api-1.16</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>space.arim.libertybans.dep</groupId>
			<artifactId>dep-spigot-api-1.17.1</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>space.arim.libertybans.dep</groupId>
			<artifactId>dep-paper-api-1.12.2</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>space.arim.libertybans.dep</groupId>
			<artifactId>dep-paper-api-1.16.5</artifactId>
			<version>${project.version}</version>
		</dependency>

		<!-- Critical parent pom -->
		<dependency>
			<groupId>space.arim.libertybans.it</groupId>
			<artifactId>invoker-it-parent</artifactId>
			<version>${project.version}</version>
			<type>pom</type>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>spigot</id>
			<url>https://hub.spigotmc.org/nexus/content/repositories/public/</url>
		</repository>
		<repository>
			<id>paper</id>
			<url>https://repo.papermc.io/repository/maven-public/</url>
		</repository>
		<repository>
			<id>paper-snapshots</id>
			<url>https://repo.papermc.io/repository/maven-snapshots/</url>
		</repository>
		<repository>
			<id>paper-releases</id>
			<url>https://repo.papermc.io/repository/maven-releases/</url>
		</repository>
		<repository>
			<id>opencollab-releases</id>
			<url>https://repo.opencollab.dev/maven-releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>opencollab-snapshots</id>
			<url>https://repo.opencollab.dev/maven-snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
		</repository>
	</repositories>
</project>
