<!--
  ~ LibertyBans-bootstrap
  ~ Copyright © 2026 Anand Beh
  ~
  ~ LibertyBans-bootstrap is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Lesser General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ LibertyBans-bootstrap is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public License
  ~ along with LibertyBans-bootstrap. If not, see <https://www.gnu.org/licenses/>
  ~ and navigate to version 3 of the GNU Lesser General Public License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>space.arim.libertybans.dep</groupId>
		<artifactId>dep-parent</artifactId>
		<version>1.2.0-M1-SNAPSHOT</version>
	</parent>

	<artifactId>dep-spigot-api</artifactId>

	<properties>
		<dep.enforce-phase>initialize</dep.enforce-phase>
		<dep.file-name>org.spigotmc.spigot-api</dep.file-name>
		<dep.jar-sig>339bdfb2daee3ffccd9f4adce9e56c0b09e587ea1347d088e8d39a1d2dd14a65edbbe85ad06481a55d1acbe04a459f1bf6447b139f1a06d6baef8f507a670799</dep.jar-sig>
		<dep.pom-sig>f9a826f8cb89db8cbb4611a66b289067a688576b0b07ba9703600b0d4e8a525a85650b1e61afd6bba74904c644dc7da9a7845d37d029e33a072beebe40d27357</dep.pom-sig>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.spigotmc</groupId>
			<artifactId>spigot-api</artifactId>
		</dependency>
		<dependency>
			<groupId>space.arim.libertybans.dep</groupId>
			<artifactId>dep-bungeecord-chat-1.8</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>spigot</id>
			<url>https://hub.spigotmc.org/nexus/content/repositories/public/</url>
		</repository>
	</repositories>
</project>
