<!--
  ~ LibertyBans-bootstrap
  ~ Copyright © 2026 Anand Beh
  ~
  ~ LibertyBans-bootstrap is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Lesser General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ LibertyBans-bootstrap is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public License
  ~ along with LibertyBans-bootstrap. If not, see <https://www.gnu.org/licenses/>
  ~ and navigate to version 3 of the GNU Lesser General Public License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>space.arim.libertybans</groupId>
		<artifactId>bans-parent</artifactId>
		<version>1.2.0-M1-SNAPSHOT</version>
	</parent>

	<artifactId>bans-bootstrap-parent</artifactId>
	<packaging>pom</packaging>

	<properties>
		<deployment.deploy-url>https://maven.cloudsmith.io/anand-beh/lesser-gpl3/</deployment.deploy-url>
	</properties>

	<licenses>
		<license>
			<name>GNU Lesser General Public License, Version 3</name>
			<url>https://www.gnu.org/licenses/lgpl-3.0-standalone.html</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<modules>
		<module>bootstrap</module>
		<module>dependency</module>
		<module>invoker-it-parent</module>
		<module>invoker-it-setup</module>
	</modules>
</project>
