name: Artifact checksum preservation

on:
  pull_request_target:
    branches: [ '**' ]

jobs:
  block-maven-checksum-modification:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Prevent existing Maven checksum files from being modified
        uses: xalvarez/prevent-file-change-action@v3.0.1
        with:
          pattern: ^\.mvn\/artifact-checksums\/.+
          allowNewFiles: true
  block-gradle-checksum-modification:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Prevent Gradle verification file from being modified
        uses: xalvarez/prevent-file-change-action@v3.0.1
        with:
          pattern: .*gradle\/verification-metadata\.xml
          trustedAuthors: A248
