name: Artifact checksum preservation

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]
    branches: [ '**' ]

jobs:
  maven-artifact-checksums:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Prevent existing Maven checksum files from being modified
        uses: xalvarez/prevent-file-change-action@v3.0.1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: ^\.mvn\/artifact-checksums\/.+
          allowNewFiles: true
  gradle-verification-metadata:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Prevent Gradle verification file from being modified
        uses: xalvarez/prevent-file-change-action@v3.0.1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: .*gradle\/verification-metadata\.xml
          trustedAuthors: A248
